#!/bin/bash

filename=cpu_usage

while :
do
        curr=$(top -bn 1 | grep "Cpu")
        echo "$(date  "+Date::%d/%m/%y  Time::%H:%M:%S") us : $(echo $curr | awk '{print $2}') sy : $(echo $curr | awk '{print $4}') " >> $filename
        sleep 10
done
