#!/bin/bash


pass() {

        local password=$1
        local min_l=8

        if [ ${#password} -gt $min_l ] && [[ $password =~ ^[a-zA-z0-9]+$ ]]
        then
                echo "Password is of correct length and is alphanumeric"
                return 0
        else
                echo "Try another password"
                return 1
        fi


}

read -p "Enter the password: " psd
pass "${psd}"
